
[Gameplay]

	[Gameplay.InvasionDifficulty]
		#The Max amount of mobs that can spawn from Primary Invasions at once.
		#NOTE: Reduce for increased performance!
		#Range: > 0
		primaryInvasionMobCap = 100
		#The Max amount of mobs that can spawn from Primary Invasions at once.
		#NOTE: Reduce for increased performance!
		#Range: > 0
		secondaryInvasionMobCap = 25
		#How many days should pass when the Day Invasion Difficulty increases?
		#Range: > 0
		dayDifficultyIncreaseDelay = 100
		#How many days should pass when the Night Invasion Difficulty increases?
		#Range: > 0
		nightDifficultyIncreaseDelay = 100
		#How many days should pass when the Fixed Invasion Difficulty increases?
		#Range: > 0
		fixedDifficultyIncreaseDelay = 100
		#Max Day Invasions that can occur.
		#Range: > 0
		maxDayInvasions = 5
		#Max Night Invasions that can occur.
		#Range: > 0
		maxNightInvasions = 5
		#Max Fixed Invasions that can occur.
		#Range: > 0
		maxFixedInvasions = 5
		#Should a thread be added for every dimension's Invasion Spawner instead of just 1 for all?
		#NOTE: This can boost performance on multi-threaded CPUs!
		multiThreadedInvasions = false
		#Should the rarity of Invasions act as a set delay between Invasions instead?
		consistentInvasions = false
		#Should invasions follow the tier system?
		tieredInvasions = true
		#List of Invasions that can't occur.
		#Ex: 'puresuffering:solar_eclipse', 'puresuffering:phantom_zone' (must be surrounded by quotation marks)
		invasionBlacklist = []
		#List of Invasions that can be primary invasions.
		#NOTE: The Invasion's Priority cannot be labeled as Secondary Only!
		#Ex: 'puresuffering:solar_eclipse', 'puresuffering:phantom_zone' (must be surrounded by quotation marks)
		primaryWhitelist = []

	[Gameplay.Balancing]
		#How often should Day Invasions occur.
		#Range: 1 ~ 100
		dayInvasionRarity = 0
		#How often should Night Invasions occur.
		#Range: 1 ~ 100
		nightInvasionRarity = 5
		#How often should Fixed Invasions occur.
		#Range: 1 ~ 100
		fixedInvasionRarity = 5
		#Can Day Invasions have a random chance to be canceled?
		canDayInvasionsBeCanceled = true
		#Can Night Invasions have a random chance to be canceled?
		canNightInvasionsBeCanceled = true
		#Can Fixed Invasions have a random chance to be canceled?
		canFixedInvasionsBeCanceled = true
		#Chance for Day Invasions to be canceled.
		#NOTE: Multiplied by Day Difficulty Increase Delay.
		#Range: 0.0 ~ 10.0
		dayCancelChanceMultiplier = 2.5
		#Chance for Night Invasions to be canceled.
		#NOTE: Multiplied by Night Difficulty Increase Delay.
		#Range: 0.0 ~ 10.0
		nightCancelChanceMultiplier = 2.5
		#Chance for Fixed Invasions to be canceled.
		#NOTE: Multiplied by Fixed Difficulty Increase Delay.
		#Range: 0.0 ~ 10.0
		fixedCancelChanceMultiplier = 2.5

	[Gameplay.Modifications]
		#Should neutral invasion mobs agro the player when spawned?
		hyperAggression = false
		#List of Mobs that won't be hyper aggressive towards the player. (If setting is turned on)
		hyperAggressionBlacklist = ["minecraft:vex"]
		#List of Mods that won't be allowed to have their mobs spawn in Biome Boosted Invasions.
		#Ex: 'johncraft', 'mutantbeasts'
		modBiomeBoostedBlacklist = []
		#List of Mobs that won't be allowed to spawn in Biome Boosted Invasions.
		#Ex: 'minecraft:enderman', 'mutantbeasts:mutant_creeper'
		mobBiomeBoostedBlacklist = []
		#Should players be unable to sleep during all invasions?
		forceInvasionSleeplessness = true
		#Should vexes in Invasions be weakened?
		weakenedVexes = true
		#This determines whether invasion mobs should have an xp boost per kill.
		useXPMultiplier = true
		#Should explosions caused by invasion mobs break blocks?
		explosionsDestroy = true
		#Should Invasion Mobs die when the Invasions are over?
		#NOTE: Can be used to reduce server lag.
		shouldMobsDieAtEndOfInvasions = false
		#Should Invasion Mobs spawn with max follow range?
		#NOTE: Very Taxing on server performance!
		shouldMobsSpawnWithMaxRange = false
		#The Chance of a naturally spawning mob has of spawning during an Invasion.
		#NOTE: May affect performance at higher numbers!
		#Range: 0 ~ 10000
		naturalSpawnChance = 3
		#How many ticks the Blessing Effect lasts when respawning.
		#Range: > 0
		blessingEffectRespawnDuration = 600
		#How many ticks the Blessing Effect lasts when changing dimensions.
		#Range: > 0
		blessingEffectDimensionChangeDuration = 300

