
["Fuel Items"]
	#Defines items that can use as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	Boiler = [["minecraft:coal", 37], ["minecraft:charcoal", 37], ["minecraft:coal_block", 333], ["minecraft:magma_block", 333], ["minecraft:lava_bucket", 1000]]
	Icebox = [["minecraft:snowball", 37], ["minecraft:clay", 37], ["minecraft:snow_block", 333], ["minecraft:water_bucket", 333], ["minecraft:ice", 333], ["minecraft:packed_ice", 1000]]
	#Negative values indicate cold fuel
	Hearth = [["minecraft:coal", 37], ["minecraft:charcoal", 37], ["minecraft:coal_block", 333], ["minecraft:magma_block", 333], ["minecraft:lava_bucket", 1000], ["minecraft:snowball", -37], ["minecraft:clay", -37], ["minecraft:snow_block", -333], ["minecraft:water_bucket", -333], ["minecraft:ice", -333], ["minecraft:packed_ice", -1000]]

["Soulspring Lamp"]
	#Defines the items that the Soulspring Lamp can use as fuel and their values
	#Format: ["item-id-1", "item-id-2", ...etc]
	"Fuel Items" = [["cold_sweat:soul_sprout", 4], ["#minecraft:warped_stems", 1], ["#minecraft:crimson_stems", 1]]
	#Defines the dimensions that the Soulspring Lamp can be used in
	#Format: ["dimension-id-1", "dimension-id-2", ...etc]
	"Valid Dimensions" = ["minecraft:the_nether"]

[Insulation]
	#Defines the items that can be used for insulating armor in the Sewing Table
	#Format: [["item_id", cold, hot], ["item_id", cold, hot], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#"cold": The amount of cold insulation the item provides.
	#"hot": The amount of heat insulation the item provides.
	"Insulation Ingredients" = [["minecraft:leather", 1.0, 0.0], ["farmersdelight:straw", 0.0, 1.0], ["#minecraft:wool", 2.0, 0.0], ["minecraft:honeycomb", 0.0, 2.0], ["immersiveengineering:hemp_fabric", 3.0, 0.0], ["cold_sweat:hoglin_hide", 0.0, 3.0], ["cold_sweat:goat_fur", 4.0, 0.0], ["minecraft:slime_ball", 0.0, 4.0]]
	#Defines insulation items that have the special "chameleon molt" effect
	#Format: [["item_id", insulation, adaptSpeed], ["item_id", insulation, adaptSpeed], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#"insulation": The amount of insulation the item provides. Will adjust to hot/cold based on the environment.
	#"adaptSpeed": The speed at which the item adapts to the current temperature. Higher values mean faster adaptation (from 0 to 1).
	"Adaptive Insulation Ingredients" = [["immersiveengineering:ersatz_leather", 1.5, 0.0085], ["#forge:tough_hides", 1.0, 0.005], ["farmersdelight:canvas", 0.5, 0.0015], ["#forge:mutation_hides", 2.0, 0.01]]
	#Defines the items that provide insulation when worn
	#Format: [["item_id", amount], ["item_id", amount], ...etc]
	"Insulating Armor" = [["minecraft:leather_helmet", 4, 4], ["minecraft:leather_chestplate", 6, 6], ["minecraft:leather_leggings", 5, 5], ["minecraft:leather_boots", 4, 4], ["cold_sweat:hoglin_headpiece", 0, 8], ["cold_sweat:hoglin_tunic", 0, 12], ["cold_sweat:hoglin_trousers", 0, 10], ["cold_sweat:hoglin_hooves", 0, 8], ["cold_sweat:goat_fur_cap", 8, 0], ["cold_sweat:goat_fur_parka", 12, 0], ["cold_sweat:goat_fur_pants", 10, 0], ["cold_sweat:goat_fur_boots", 8, 0]]
	#Defines how many insulation slots armor pieces have
	#Format: [head, chest, legs, feet]
	"Insulation Slots" = [4, 6, 5, 4]

[Consumables]
	#Defines items that affect the player's temperature when consumed
	#Format: [["item_id", amount], ["item_id", amount], ...etc]
	#Negative values are cold foods, positive values are hot foods
	"Temperature-Affecting Foods" = []
	#Defines the amount a player's body temperature will change by when using a waterskin
	#Range: > 0
	"Waterskin Strength" = 50

