#Show the config menu button in the Options menu
"Enable In-Game Config" = true
#Overrides all other config options for easy difficulty management
#This value is changed by the in-game config. It does nothing otherwise.
#Range: 1 ~ 5
Difficulty = 3

["Item settings"]
	#Fire Resistance blocks all hot temperatures
	"Fire Resistance Immunity" = true
	#Ice Resistance blocks all cold temperatures
	"Ice Resistance Immunity" = true
	#Thermometer item is required to see world temperature
	"Require Thermometer" = true

["Misc temperature-related things"]
	#Sets whether damage scales with difficulty
	"Damage Scaling" = true
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Prevent Sleep When in Danger" = true

["Details about how the player is affected by temperature"]
	#Minimum habitable temperature (default: 0.42857142857142855)
	#Range: -Infinity ~ Infinity
	"Minimum Habitable Temperature" = 0.42857142857142855
	#Maximum habitable temperature (default: 1.619047619047619)
	#Range: -Infinity ~ Infinity
	"Maximum Habitable Temperature" = 1.619047619047619
	#Rate at which the player's body temperature changes (default: 1.0 (100%))
	#Range: 0.0 ~ Infinity
	"Rate Multiplier" = 1.0

["Temperature Effects"]

	["Temperature Effects".Hot]
		#When set to true, the camera will sway randomly when the player is too hot
		"Camera Sway" = true
		#When set to true, the player's view distance will decrease when they are too hot
		"Heatstroke Fog" = true

	["Temperature Effects".Cold]
		#When set to true, some of the player's hearts will freeze when they are too cold, preventing regeneration
		"Freezing Hearts" = true
		#When set to true, the player's attack knockback will be reduced when they are too cold
		"Cold Knockback Reduction" = true
		#When set to true, the player's movement speed will be reduced when they are too cold
		"Cold Slowness" = true
		#When set to true, the player's mining speed will be reduced when they are too cold
		"Cold Mining Fatigue" = true

["Grace Period Details"]
	#Grace period length in ticks (default: 6000)
	#Range: > 0
	"Grace Period Length" = 6000
	#Enables the grace period (default: true)
	"Grace Period Enabled" = true

[Hearth]
	#How strong the hearth is (default: 0.5)
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.5

["Cold Soul Fire"]
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

["Block Temperatures"]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range (max 7)>, <*true/false: falloff>, <*max effect>, *<predicates>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: the temperature of the block, in Minecraft units
	#falloff: the block is less effective as distance increases
	#max effect: the maximum temperature change this block can cause to a player (even with multiple blocks)
	#predicates: the state that the block has to be in for the temperature to be applied (lit=true for a campfire, for example).
	#Multiple predicates can be used by separating them with commas (i.e: "lit=true,waterlogged=false")
	BlockTemps = [["minecraft:soul_fire", -0.2, 7, true, 0.8], ["minecraft:fire", 0.2, 7, true, 0.8], ["minecraft:magma_block", 0.15, 3, true, 0.6], ["minecraft:soul_campfire", -0.2, 3, true, 0.6, "lit=true"], ["minecraft:ice", -0.1, 4, true, 0.5], ["minecraft:packed_ice", -0.2, 4, true, 1.0], ["minecraft:blue_ice", -0.3, 4, true, 1.0]]

