
#Increase melee damage
[strength]
	#Range: > 1
	maxLevel = 20
	#Range: > 1
	costPerLevel = 40
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.075
	prerequisites = ""

#Increase critical chance
[criticalstrike]
	#Range: > 1
	maxLevel = 20
	#Range: > 1
	costPerLevel = 50
	#Range: 0.0 ~ 1.0
	bonusPerLevel = 0.05
	prerequisites = "strength:4"
	#If set to true, vanilla crits will be disabled
	disableVanillaCrits = true

#Increase bow charge speed
[quickdraw]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 50
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05
	prerequisites = ""

#Increase arrow velocity
[arrowspeed]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 40
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.03
	prerequisites = "quick_draw:4"

#Decrease damage taken
[ironskin]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 40
	#Range: 0.0 ~ 1.0
	bonusPerLevel = 0.03
	prerequisites = "strength:7"

#Increase speed while sneaking
[sneakspeed]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 40
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.075
	prerequisites = ""

#Every X ticks, chance to grow crops around
[greenthumb]
	#Range: > 20
	greenThumbTickRate = 100
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 40
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.015
	prerequisites = ""

#Chance to gather extra crops on harvest
[harvestproficiency]
	#Range: > 1
	maxLevel = 20
	#Range: > 1
	costPerLevel = 50
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05
	#Range: 0.0 ~ 1.7976931348623157E308
	potentialLootBound = 1.0
	prerequisites = "green_thumb:4"

#Chance to gather extra skins from animals
[skinning]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 40
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.075
	#Range: 0.0 ~ 1.7976931348623157E308
	potentialLootBound = 1.0
	prerequisites = ""

#Chance to drop extra meat from animals
[meatgathering]
	#Range: > 1
	maxLevel = 20
	#Range: > 1
	costPerLevel = 50
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05
	#Range: 0.0 ~ 2.147483647E9
	potentialLootBound = 1.0
	prerequisites = "skinning:4"

#Increase speed under water
[swimspeed]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 40
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.075
	prerequisites = ""

#Decrease total cooking time
[cookingspeed]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 50
	#Range: 0.0 ~ 1.0
	bonusPerLevel = 0.09
	prerequisites = ""

#Increase stone mining speed
[stonecutting]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 40
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05
	prerequisites = ""

#Chance to increase yield from ores
[prospecting]
	#Range: > 1
	maxLevel = 20
	#Range: > 1
	costPerLevel = 50
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05
	#Range: 0.0 ~ 1.7976931348623157E308
	potentialLootBound = 1.0
	prerequisites = "stonecutting:4"

#Increase wood chopping speed
[woodcutting]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 40
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05
	prerequisites = ""

#Random chance to find treasure while digging
[treasurehunting]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 60
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.0125
	#Range: > 1
	rareTreasureWeight = 1
	#Range: > 1
	uncommonTreasureWeight = 3
	#Range: > 1
	commonTreasureWeight = 6
	prerequisites = "prospecting:3,stonecutting:8"

#Decrease fall damage taken
[softlanding]
	#Range: > 1
	maxLevel = 20
	#Range: > 1
	costPerLevel = 20
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.02
	prerequisites = ""

#Increase movement speed while sprinting
[sprintspeed]
	#Range: > 1
	maxLevel = 10
	#Range: > 1
	costPerLevel = 40
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.04
	prerequisites = ""

