
#Combat Specialization
#Protector of the realm
#Earn bonus XP on kill
[combat]
	#Define how much levels the player needs to unlock the Combat specialization
	#Range: > 0
	cost = 10
	#Define the maximum amount of bonus XP on kill, based on the original dropped XP
	#Range: 0.0 ~ 1.7976931348623157E308
	bonus = 1.0

#Crafting Specialization
#Craft and gather resources
#Earn bonus XP when crafting
[crafting]
	#Define how much levels the player needs to unlock the Crafting specialization
	#Range: > 0
	cost = 10
	#Define the multiplier for the amount of bonus XP when crafting
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusMultiplier = 3.0
	#Define items which when crafted will grant no bonus XP
	blacklist = "modid:example_item,modid:another_example_item"

#Mining Specialization
#Branch mining is for cowards
#Earn bonus XP for mining ores
[mining]
	#Define how much levels the player needs to unlock the Mining specialization
	#Range: > 0
	unlockCost = 10
	#Define the amount of bonus XP dropped when mining, based on the original dropped XP
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusBound = 3.0

