
[Extraction]
	#The Flux the Pumpjack requires each tick to pump
	#Default: 1024
	pumpjack_consumption = 1024
	#The amount of mB of oil a Pumpjack extracts per tick
	#Default: 15
	pumpjack_speed = 15
	#The Flux the Derrick requires each tick to operate
	#Default: 512
	derrick_consumption = 512

[Refining]
	#A modifier to apply to the energy costs of every Distillation Tower recipe
	#Default: 1.0
	distillationTower_energyModifier = 1.0
	#A modifier to apply to the time of every Distillation recipe. Can't be lower than 1
	#Default: 1.0
	distillationTower_timeModifier = 1.0
	#A modifier to apply to the energy costs of every Coker Tower recipe
	#Default: 1.0
	cokerUnit_energyModifier = 1.0
	#A modifier to apply to the time of every Coker recipe. Can't be lower than 1
	#Default: 1.0
	cokerUnit_timeModifier = 1.0
	#A modifier to apply to the energy costs of every High-Pressure Refinery Unit recipe
	#Default: 1.0
	hydrotreater_energyModifier = 1.0
	#A modifier to apply to the time of every High-Pressure Refinery Unit recipe. Can't be lower than 1
	#Default: 1.0
	hydrotreater_timeModifier = 1.0

[Generation]
	#List of Portable Generator fuels. Format: fluid_name, mb_used_per_second, flux_produced_per_tick
	generator_fuels = ["immersivepetroleum:naphtha, 9, 256", "immersivepetroleum:gasoline, 6, 256", "immersivepetroleum:benzene, 6, 256"]

[Miscellaneous]
	#List of Motorboat fuels. Format: fluid_name, mb_used_per_tick
	boat_fuels = ["immersivepetroleum:gasoline, 1", "immersivepetroleum:naphtha, 2", "immersivepetroleum:benzene, 2"]
	#Automatically unlock IP recipes for new players
	#Default: true
	autounlock_recipes = true
	#Set to false to disable the asphalt block boosting player speed
	#Default: true
	asphalt_speed = false

