#Whether these limitations will be imposed to players
limitations_imposed = true

["Action Permissions"]
	permit_BreakfallReady = true
	permit_CatLeap = true
	permit_ClimbUp = true
	permit_ClingToCliff = true
	permit_Crawl = true
	permit_Dive = true
	permit_Dodge = false
	permit_FastRun = true
	permit_Flipping = true
	permit_HangDown = true
	permit_HorizontalWallRun = true
	permit_JumpFromBar = true
	permit_QuickTurn = true
	permit_Roll = true
	permit_Slide = true
	permit_Tap = true
	permit_Vault = true
	permit_WallJump = true
	permit_WallSlide = true

[Stamina]
	#Limitation of max stamina
	#Range: 300 ~ 100000
	max_value_of_stamina = 20000
	#Limitation of max stamina recovery
	#Range: 1 ~ 10000
	max_value_of_stamina_recovery = 1500
	#Allow Infinite Stamina
	infinite_stamina = true

	[Stamina."Least Consumption"]
		#Range: 0 ~ 10000
		stamina_consumption_of_BreakfallReady = 0
		#Range: 0 ~ 10000
		stamina_consumption_of_CatLeap = 150
		#Range: 0 ~ 10000
		stamina_consumption_of_ClimbUp = 150
		#Range: 0 ~ 10000
		stamina_consumption_of_ClingToCliff = 2
		#Range: 0 ~ 10000
		stamina_consumption_of_Crawl = 0
		#Range: 0 ~ 10000
		stamina_consumption_of_Dive = 0
		#Range: 0 ~ 10000
		stamina_consumption_of_Dodge = 80
		#Range: 0 ~ 10000
		stamina_consumption_of_FastRun = 2
		#Range: 0 ~ 10000
		stamina_consumption_of_Flipping = 80
		#Range: 0 ~ 10000
		stamina_consumption_of_HangDown = 3
		#Range: 0 ~ 10000
		stamina_consumption_of_HorizontalWallRun = 2
		#Range: 0 ~ 10000
		stamina_consumption_of_JumpFromBar = 100
		#Range: 0 ~ 10000
		stamina_consumption_of_QuickTurn = 0
		#Range: 0 ~ 10000
		stamina_consumption_of_Roll = 100
		#Range: 0 ~ 10000
		stamina_consumption_of_Slide = 0
		#Range: 0 ~ 10000
		stamina_consumption_of_Tap = 100
		#Range: 0 ~ 10000
		stamina_consumption_of_Vault = 50
		#Range: 0 ~ 10000
		stamina_consumption_of_WallJump = 120
		#Range: 0 ~ 10000
		stamina_consumption_of_WallSlide = 2

