
[milestones]
	#Number of hearts you start out with.
	#Range: 0 ~ 1000
	baseHearts = 10
	#Number of hearts you gain for reaching a new milestone.
	#Range: 0 ~ 1000
	heartsPerMilestone = 1
	#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
	milestones = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150]

[filtering]
	#Foods in this list won't affect the player's health nor show up in the food book.
	blacklist = ["alexsmobs:cosmic_cod",
				"undead_revamp2:fizzysnowgoo",
				"undead_revamp2:huntereye",	
				"undead_revamp2:spiiterfriedegg",
				"apocalypsenow:beer",
				"apocalypsenow:tomato",
				"apocalypsenow:butter",
				"apocalypsenow:canteen_41",
				"apocalypsenow:canteen_42",
				"apocalypsenow:canteen_43",
				"apocalypsenow:canteen_44",
				"apocalypsenow:chicken_wing",
				"apocalypsenow:cooked_chicken_wing",
				"apocalypsenow:corn",
				"apocalypsenow:chocolate_bar",
				"apocalypsenow:cheese",
				"apocalypsenow:macandcheese",
				"apocalypsenow:marmalade",
				"apocalypsenow:nonalcoholic_beer",
				"apocalypsenow:nutrition_bar",
				"apocalypsenow:vitamins",
				"apocalypsenow:contaminated_water",
				"apocalypsenow:cooked_canned_chilie",
				"apocalypsenow:cooked_canned_food",
				"apocalypsenow:cooked_canned_soup",
				"apocalypsenow:cooked_canned_beens",
				"apocalypsenow:open_canned_chili",
				"apocalypsenow:open_canned_strawberry",
				"apocalypsenow:open_canned_corn",
				"apocalypsenow:open_canned_soup",
				"apocalypsenow:open_canned_food",
				"apocalypsenow:open_canned_beens",
				"apocalypsenow:open_dogs_food",
				"apocalypsenow:wine",
				"apocalypsenow:water",
				"apocalypsenow:orange",
				"apocalypsenow:tomato",
				"apocalypsenow:milk",
				"apocalypsenow:lettuce",
				"apocalypsenow:fried_egg",
				"apocalypsenow:fries",
				"apocalypsenow:hamburger",
				"apocalypsenow:donut",
				"apocalypsenow:dead_rat",
				"apocalypsenow:dead_cockroach",
				"apocalypsenow:cooked_rat",
				"apocalypsenow:cooked_cockroach",
				"apocalypsenow:cream_cracker",
				"artifacts:eternal_steak",
				"artifacts:everlasting_beef"]
	#When this list contains anything, the blacklist is ignored and instead only foods from here count.
	whitelist = []
	#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
	#Range: 0 ~ 1000
	minimumFoodValue = 1

[miscellaneous]
	#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = true
	#If true, eating foods outside of survival mode (e.g. creative/adventure) is not tracked and thus does not contribute towards progression.
	limitProgressionToSurvival = false

