
[mobs]
	blacklist = []
	whitelist = []
	always_show_level = false
	show_level_when_looking_at = false
	exp_bonus_per_level = 0.2
	hidden_levels = []

[attributes]
	attribute_bonuses = [["minecraft:generic.movement_speed", 0.0], ["minecraft:generic.flying_speed", 0.0], ["minecraft:generic.attack_damage", 0.025], ["minecraft:generic.armor", 0.0], ["minecraft:generic.max_health", 0.05], ["autoleveling:monster.projectile_damage_bonus", 0.0], ["autoleveling:monster.explosion_damage_bonus", 0.0]]

[default_leveling_settings]
	starting_level = 1
	max_level = 100
	levels_per_distance = 5.0E-4
	levels_per_deepness = 0.0
	random_level_bonus = 0

