
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 490660
	#The name of the modpack
	modpackName = "DeceasedCraft"
	#The version of the modpack
	modpackVersion = "v5.3.5"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

