
#General settings
[General]
	#Determines the spoilrate in specific containers [Syntax: tileentity:spoil_rate]
	#Examples: "minecraft:shulker_box,0" would make shulker boxes not spoil food
	#"cookingforblockheads:fridge,0.2" would make a cooking for blockheads fridge spoil at 20% of the usual spoilrate
	containerModifier = ["minecraft:shulker_box,0"]
	#Defines the default total amount of spoiling updates for each food item 
	#(For example, a defaultSpoilTime of 40 means any default food item will have 40 total updates before it spoils. 
	#This can be altered when custom food spoiling is set using a datapack) [default: 30]
	#Range: > 1
	spoilRate = 30
	#When enabled Spoiled initializes spoiling for all vanilla food [default: true]
	initializeSpoiling = true
	#When enabled enables a special recipe to merge spoiling food together [default: false]
	mergeSpoilingFood = false
	#When enabled Spoiled makes every edible item spoil into the specified Spoil Item (This overwrites json spoiling completely) [default: false]
	spoilEverything = false
	#Defines a list of items that you do not want to spoil when 'spoilEverything' is enabled
	spoilEverythingBlacklist = ["minecraft:rotten_flesh", "minecraft:enchanted_golden_apple"]
	#Defines the total amount of spoiling updates that is used by the default initialized spoiling when 'initializeSpoiling' is enabled 
	#(If the 'spoilRate' is 10 and the 'defaultSpoilTime' is set to 20 then the food will spoil after 20 * 10 seconds = 200 seconds) [default: 40]
	#Range: > 1
	defaultSpoilTime = 40
	#Defines the item the foods vanilla foods will turn into when spoiled (if empty it will clear the spoiling item) [default: 'minecraft:rotten_flesh']
	defaultSpoilItem = "minecraft:rotten_flesh"

