
[modcompat]
	#Controls whether to check for Serene Seasons for compatibility (Mobs will only breed during specific seasons).
	serene_seasons = true
	#Controls whether to check for YUNG's Better Caves (Reduces the rate at which Underground mobs are placed).
	better_caves = true
	#Controls whether to check for Patchouli compatibility (For the purpose of granting the Root advancement).
	patchouli = true

[mobcontrol]
	#Chance, defined as once every N tries, where N is this value, for a new mob to be generated when a burrow spawns a new mob.
	#Range: 0 ~ 100
	burrowRepopulationChance = 10
	#Critters further than this value from any Player will despawn into their Burrow (only if they have a Burrow assigned).
	#Range: > 0
	critterSpawnRange = 40
	#This toggle can used to fully disable the spawning of all UntamedWilds entities, giving flexibility if somebody chooses to use alternative mob spawning methods.
	masterspawner = true
	#If a mob were to be unable to spawn on the ground (due to terrain collisions), check again N blocks above the floor, where N is this value. Set to 0 to disable, higher values will mean mobs spawning on top of taller trees
	#Range: 0 ~ 256
	treeSpawnBias = 4
	#Prevent mobs and burrows from spawning in the defined dimensions.
	dimensionBlacklist = []

[gencontrol]
	#Frequency of Reeds, 1 in N chunks will generate Reeds (0 to disable)
	#Range: > 0
	freqreeds = 4
	#Frequency of Flora, 1 in N chunks will generate random Flora (0 to disable)
	#Range: > 0
	freqflora = 4
	#Controls whether to add Anemones and their associated items to oceans.
	anemone = true
	#Controls whether to spawn random Flora in the world
	bush = true
	#Prevent spawns of Reeds in these biomes
	reed_blacklist = []
	#Frequency of Apex Predators, 1 in N chunks will generate with an Apex Predator (0 to disable)
	#Range: > 0
	freqapex = 64
	#Frequency of Critters, 1 in N chunks will generate with Critters (0 to disable)
	#Range: > 0
	freqcritter = 6
	#Controls whether to spawn Amazon Sword in Swamp/Jungle biomes
	algae = true
	#Frequency of Herbivores, 1 in N chunks will generate with an Apex Predator (0 to disable)
	#Range: > 0
	freqherbivore = 48
	#Frequency of Sessile Ocean Mobs, 1 in N chunks will generate with Sessile Mobs (0 to disable)
	#Range: > 0
	freqsessile = 8
	#Frequency of Freshwater Mobs, 1 in N chunks will generate with Freshwater Mobs (0 to disable)
	#Range: > 0
	freqwater = 8
	#Prevent spawns of Flora in these biomes
	flora_blacklist = []
	#Controls whether to spawn Reeds in River/Swamp biomes
	reeds = true
	#Frequency of Algae, abstract value (0 to disable)
	#Range: > 0
	freqalgae = 1
	#Prevent spawns of Algae in these biomes
	algae_blacklist = ["minecraft:frozen_ocean", "minecraft:deep_frozen_ocean"]
	#Probability that an Underground block in a cave will attempt to spawn a mob (0 to disable). If YUNG's Better Caves is installed, this value is further reduced to 0.33x
	#Range: 0.0 ~ 1.0
	probunderground = 4.0E-4
	#Frequency of Ocean Mobs, 1 in N chunks will generate with Ocean Mobs (0 to disable)
	#Range: > 0
	freqocean = 16
	#Controls whether to use Burrows to spawn Critters, instead of having them clog up the Spawns
	burrows = true
	#Controls whether to add Tree Orchids (NOT YET IMPLEMENTED)
	tree_orchid = true
	#Prevent flora and other blocks (but not Burrows) from generating in the defined dimensions.
	dimensionFeatureBlacklist = []

[gamerules]
	#Pregnancy time is only used as a cooldown, babies pop out instantly like in Vanilla.
	easy_breeding = false
	#Defines whether animals should breed without Player intervention.
	natural_breeding = true
	#Range up to which the Spyglass will identify mobs and give information, this length is not in blocks, and is roughly equivalent to a Render distance of 12.
	#Range: > 0
	spyglass_range = 5000
	#Defines whether certain large predators will be angered if a player approaches them while they are sleeping.
	angry_sleepers = true
	#Allows mobs to spawn as fully random species, ignoring Biomes and Rarity.
	random_species = false
	#Should 'Grazing' mobs destroy Tall Grass and/or turn Grass into dirt blocks (like Vanilla Sheep do).
	grazer_griefing = true
	#If a mob was not able to spawn in a certain position due to existing blocks, try again with this vertical offset. A value of 0 will disable it (you should never see a mob on top of a tree), a value too high will lead to fall damage.
	#Range: 0 ~ 128
	spawn_height_bias = 4
	#If set to false, prevents mobs from dropping eggs
	mobs_drop_eggs = false
	#Should mobs with Rare skins generate in the wild (if defined through assets)
	wild_rare_skins = true
	#Whether breeding requires a Male and a Female to produce offspring/eggs. (Warning: may lead to uncontrolled spawns of eggs)
	gendered_breeding = true
	#Features scientific names in various descriptions (eg. for mobs inside Cage Traps).
	scientific_names = true
	#Defines whether certain critters will become angry if a mob/player 'steps' on them, by coming too close.
	contact_agression = true
	#Disable this option to have tamed mobs respawn in their home with half a Heart if they were to 'die' (IMPORTANT: This gamerule is NOT fully functional and using it as a free get-out-of-jail card is bound to be disappointing, use at your own risk).
	hardcore_death = true
	#Should mobs potentially destroy the terrain? Keep in mind 'mobGriefing' is still required
	mob_griefing = false
	#Adds additional restrictions to mob breeding, including Biome/Temperature requirements and Overcrowding.
	hardcore_breeding = false
	#Defines how long a cycle should last, cycles are used to scale the gestation and breeding periods
	#Example values: 24000 - Day, 168000 - Week, 720000 - Month, 8760000 - Year
	#Range: 0 ~ 8760000
	cycle_length = 24000
	#Chance for a mob, out of 1, to have it's Skin replaced by a Rare skin (if any are defined through assets)
	#Range: 0.0 ~ 1.0
	rare_skin_chance = 0.05
	#Defines whether players can trigger breeding by feeding a creature's favourite item, like in vanilla.
	player_breeding = false
	#Should the vanilla Spyglass display information when a player looks at a mob. Set to false to disable.
	spyglass_behavior_change = true
	#Should the 'Sleeping' behaviour run? Disabling this option also disables the activity
	mob_sleeping = true
	#If set to false, makes mobs a lot harder to catch by preventing the capture of hostile mobs
	easy_mob_capture = true

