#[INTERNAL] Mod configuration version -- DO NOT ALTER, EVER!
version = 1

[general]
	#Set to false to disable the portable 'goo paks' that you carry in your hotbar. Paks are a useful supplement to regular temperature liners in extreme environments. Included by default; requires FULL restart if changed.
	include_goopaks = true
	#Set to false to disable special items unrelated to core PvE attribute management. Even when enabled, most special items are uncraftable and need to be included as custom loot drops, advancement rewards, or with custom crafting recipes. Requires FULL restart if changed.
	include_special_items = true
	#Set to false to disable all mod-specific additions to vanilla loot tables. Note that loot may be the only way to obtain special liners like the Tonic Membrane. Enabled by default; requires FULL restart if changed.
	enrich_loot_tables = true
	#Set to false to turn off documentation tooltips (status tips not affected). Enabled by default.
	show_doc_tooltips = true
	#Set to "true" to include crafting recipes for some liners (and materials) that are normally obtained through other mechanisms like looting or advancements. By default, only a few temperature-related PvE liners are craftable. Requires FULL restart if changed.
	special_liners_craftable = "*DEFAULT*"
	#Set to the maximum number of simple warming or cooling liners a single piece of armor can have. Note that this value can reduce an existing upper bound-- it will NOT increase an existing hardlimit. Applies to all types of armor pieces (helmets, chestplates, leggings, boots, gloves, etc.). Does NOT apply to specialty liners.
	#Range: 1 ~ 3
	thickness_limit = 3

[internal]
	#INTERNAL. Development workflow enabled. Do NOT enable in regular environment.
	debug_mode = false
	#INTERNAL. Event tracing enabled. Requires debug-mode be enabled also.
	event_tracing_mode = false

[integration]
	#Set to true to force all the basic recipes to use a mod-specific element to ensure no collisions with other mod recipes. Off by default; requires FULL restart if changed.
	super_compatibility_mode = false
	#Set to the registry ids of all modded helmets that can be worn with lining up to 3 layers thick (actual max thickness depends on armor piece). Works in conjunction with datapack tag groups. Some examples shown. Requires a restart if changed.
	helmets = ["armorplus:infused_lava_helmet", "cyclic:emerald_helmet", "cyclic:crystal_helmet"]
	#Set to the registry ids of all modded chestplates that can be worn with lining up to 3 layers thick (actual max thickness depends on armor piece). Works in conjunction with datapack tag groups. Some examples shown. Requires a restart if changed.
	chestplates = ["armorplus:infused_lava_chestplate", "cyclic:emerald_chestplate", "cyclic:crystal_chestplate"]
	#Set to true to allow any mod's armor pieces to be altered with any type of lining provided this is not denied explicitly by an active datapack. If true, all other armor inclusion criteria is ignored. Disabled by default; requires restart if changed.
	allow_all_armor = false
	#Set to "false" to disable direct integration with villager merchant trades tables. Leave as '*DEFAULT*' to permit trading depending on context and availability of other mods. Requires FULL restart if changed.
	modded_trading_allowed = "*DEFAULT*"
	#Set to false to disable the recipes to refill and recycle used goo paks. Included by default; requires FULL restart if changed.
	used_goopak_recycling = true
	#[DISABLED] Set to true to allow liners associated with baubles, trinkets, etc. If false, only armor-based liners are processed. Disabled by default; requires restart if changed.
	allow_bauble_liners = false
	#Set to the ids of mods where all armor pieces can be adjusted with liners. Modded armor not covered by the other integration categories and not defined here will not be changed with the mod's default recipes. Requires a restart if changed.
	allowed_modlist = ["armorplus", "blazegear", "craftandhunt", "dungeons_gear", "easy_steel", "enigmaticlegacy", "gardencalypso", "iceandfire", "pinklysheep", "silentgear", "survive", "thebetweenlands", "toughasnails", "twilightforest"]
	#Set to the registry ids of all modded boots that can be worn with lining up to 3 layers thick (actual max thickness depends on armor piece). Works in conjunction with datapack tag groups. Some examples shown. Requires a restart if changed.
	boots = ["armorplus:infused_lava_boots", "cyclic:emerald_boots", "cyclic:crystal_boots"]
	#Set to true to ignore gear marked as liner-unstrippable (using snips)
	ignore_unstrippable = false
	#Set to the registry ids of all modded leggings that can be worn with lining up to 3 layers thick (actual max thickness depends on armor piece). Works in conjunction with datapack tag groups. Some examples shown. Requires a restart if changed.
	leggings = ["armorplus:infused_lava_leggings", "cyclic:emerald_leggings", "cyclic:crystal_leggings"]
	#Set to false to disable this mod's related mixin code functions. Use this option if-and-only-if you need to diagnose inter-mod mixin conflicts. Disabling will NOT prevent integration of mixin plugin-- it just neuters what the mixin does runtime. Disabling in regular gameplay will alter the effectiveness of many linings.
	enable_mixins = true
	#Set to false to stop use of enchantments for some special liner features.
	use_enchantments = true

[special_items]
	#Set to false to disable Anti-friction related items specifically. Ignored unless option 'include_special_items' is turned ON. Requires GAME restart if changed.
	anti_friction = true
	#Set to false to disable check for blindness when using camouflage covering. Needed until base game makes blindness actually work for mobs. Enabled by default; applies only to camouflage covers.
	blindness_matters = true
	#Set to false to disable Happy Radiance related items specifically. Ignored unless option 'include_special_items' is turned ON. Requires GAME restart if changed.
	happyjoy_liner = true
	#Set to false to disable Awkward Membrane related items specifically. Ignored unless option 'include_special_items' is turned ON. Requires GAME restart if changed.
	tonic_membrane = true
	#Set to false to disable Camouflage Covering related items specifically. Ignored unless option 'include_special_items' is turned ON. Requires GAME restart if changed.
	camouflage_cover = true
	#Set to false to allow camouflage to be maintained even after attacking. By default if a camouflaged entity attacks a mob, that mob can now see their attacker (and target them) for some time.
	attacking_matters = true
	#Set to false to disable Hydration Pouch related items specifically. Ignored unless option 'include_special_items' is turned ON. Requires GAME restart if changed.
	hydration_pouch = true
	#Set to false to disable Enchantment Pocket related items specifically. Ignored unless option 'include_special_items' is turned ON. Requires GAME restart if changed.
	enchantment_pocket = true

