#Enable simple harvesting and replanting with right click
"Simple Harvest" = true
#Curiosity Mode: sneak + right click with on block to get info in chat
Curiosity = false
#List of crops to process with their ages
"Crops List" = ["Block{minecraft:potatoes}[age=7]", "Block{minecraft:carrots}[age=7]", "Block{minecraft:wheat}[age=7]", "Block{minecraft:beetroots}[age=3]", "Block{minecraft:nether_wart}[age=3]", "Block{farmersdelight:onions}[age=7]", "Block{farmersdelight:cabbages}[age=7]", "Block{farmersdelight:tomatoes}[age=3]"]
#Amount of XP given
#Range: > 1
"XP Amount" = 3
#Chance in % of XP orb spawning after harvest done
#Range: 1 ~ 100
Chance = 100

