
#General mod settings
[general]
	#Max awareness range for zombies
	#Range: > 0
	maxPFRangeSense = 48
	#Prevent non zombies from being attracted to light
	awareness_Light_OnlyZombies = true
	#Custom targetting sight range on top of vanilla sight based targetting
	#Range: > 0
	sightRange = 12
	#Always target closest player [performance sensitive]
	omniscient = false
	#skips line of sight check on targetting [performance sensitive]
	seeThroughWalls = false
	#Effects how far monsters will sense scents from
	#Range: > 0
	scentStrength = 24
	#Effects how far monsters will sense sound sources from
	#Range: > 0
	soundStrength = 48
	#max rate of spawning sound sources in milliseconds
	#Range: > 0
	frequentSoundThreshold = 1000
	#Range of extra random speed to give a zombie for extra spawns and zombie duplications, eg: 0 = no boost, 1 = up to double speed (works for my extra spawned mobs only)
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	zombieRandSpeedBoost = 0.1
	#The amount of delay in game ticks between processing mobs with enhanced AI, less is more frequent [performance sensitive]
	#Range: > 0
	tickRateAILoop = 40
	#how frequently the mod iterates all players, effects rates, less is more frequent
	#Range: > 0
	tickRatePlayerLoop = 40
	#How long before a mob can move around again to track a light source, or scent, or sound, increase number to reduce performance impact of mod if needed
	#Range: > 0
	tickCooldownBetweenPathfinds = 300
	#How likely zombies making noise near you will attract other zombies, higher = less likely, 0 = every time they make a noise
	#Range: > 0
	noisyZombiesReinforceOddsTo1 = 5
	#-
	debugConsole = false
	#-
	debugConsoleOmniscient = false
	#-
	debugConsoleSuperDetailed = false
	#Minimum distance required between active sense sources, prevents spamming sources [performance sensitive]
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	extraScentCutoffRange = 3.0
	#Max strength allowed for a sense, in case senses get a super high base strength or large buff
	#Range: > 0
	senseMaxStrength = 300
	#Days before all of the mods features will be activated
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	daysBeforeFeaturesActivate = 4.9E-324
	#Block breaks cause sound senses to spawn
	blockBreakEvent_Active = true
	#Block mining before it breaks cause sound senses to spawn
	blockHittingEvent_Active = true
	#Odds of hitting a block causing a sound sense, rolled per tick
	#Range: > 0
	blockHittingEvent_OddsTo1 = 20
	#Only spawn sound senses for players, if false, machines and other things will cause them too
	blockBreakEvent_PlayersOnly = false

